### ISSUE TITLE
Support nested relations

### ISSUE THREAD

**Issue by ldiebold** [tailflow/laravel-orion#17] opened 2020-12-14 03:01 UTC
Would love to be able to `include` nested relations.
Something like this:

```php
protected function includes(): array
{
  return ['business.manager'];
}
```

would be able to save a few calls to the API!

Thanks a million for this package, I absolutely love it. So beautifully written :smiley:

**Comment by alexzarbn** [comment] 2020-12-14 15:20
Hi @ldiebold,

First of all, thank you for the kind words!

Honestly, I thought this is already supported 🤔
Let me check, and I will get back to you after running a few tests.

But either way, this is definitely something that will be introduced, if it is not supported.

**Comment by alexzarbn** [comment] 2020-12-15 14:52
@ldiebold,

Found the cause - it is `RelationsResolver@guardRelations` that wipes out eager loaded _nested_ relations, because there is no "business.manager" relation on the model itself.

Will include the fix in v1.2 👌

**Comment by PascalHesselink** [comment] 2020-12-15 20:05
> @ldiebold,
> 
> Found the cause - it is `RelationsResolver@guardRelations` that wipes out eager loaded _nested_ relations, because there is no "business.manager" relation on the model itself.
> 
> Will include the fix in v1.2 👌

Would be cool if you have also a 'defaultInclude' array option so you don't have to pass them every time through the parameters. (also available for nesting).

**Comment by PascalHesselink** [comment] 2020-12-15 21:20
> @ldiebold,
> 
> Found the cause - it is `RelationsResolver@guardRelations` that wipes out eager loaded _nested_ relations, because there is no "business.manager" relation on the model itself.
> 
> Will include the fix in v1.2 👌

I'm also facing this problem, would love to see this fix! Amazing work @alexzarbn.

**Comment by ldiebold** [comment] 2020-12-16 00:32
@alexzarbn thankyou!!!

Also want to point out how beautiful your code is. Simple comments, easy to navigate... A true joy 💓

**Comment by alexzarbn** [comment] 2020-12-16 12:44
@PascalHesselink 

Thank you ~

Got it, will plan to implement the fix for this weekend.

**Comment by alexzarbn** [comment] 2020-12-16 12:46
@ldiebold 

It took a lot of refactoring to get to its current state 😄
Thank you, will keep it this way ~

**Comment by PascalHesselink** [comment] 2020-12-16 13:41
> @PascalHesselink
> 
> Thank you ~
> 
> Got it, will plan to implement the fix for this weekend.

I noticed it works when you list them up, in my case: 
```php
        return [
                'forumCategories',
                'forumCategories.threads',
                'forumCategories.threads.user',
        ];
```

But it doesn't recognise the resources, so I wanted to exclude the email from the 'user' relationship, but that didn't work through the resources. I hope you can also look to that!

**Comment by alexzarbn** [comment] 2020-12-17 14:53
@PascalHesselink,

Have you tried [explicitly setting](https://tailflow.github.io/laravel-orion-docs/guide/responses.html) the resource class?
If resources are located in non-conventional folder, indeed, it may not find them.

**Comment by PascalHesselink** [comment] 2020-12-17 16:19
> @PascalHesselink,
> 
> Have you tried [explicitly setting](https://tailflow.github.io/laravel-orion-docs/guide/responses.html) the resource class?
> If resources are located in non-conventional folder, indeed, it may not find them.

I'm using the default namespace/conventional way of creating resources. I've noticed if you want to manually 'register' them, they have to been put in a controller. In my case the 'user' relationship doesn't have a controller because it is a nested relationship.

**Comment by alexzarbn** [comment] 2020-12-21 15:50
> > @PascalHesselink,
> > Have you tried [explicitly setting](https://tailflow.github.io/laravel-orion-docs/guide/responses.html) the resource class?
> > If resources are located in non-conventional folder, indeed, it may not find them.
> 
> I'm using the default namespace/conventional way of creating resources. I've noticed if you want to manually 'register' them, they have to been put in a controller. In my case the 'user' relationship doesn't have a controller because it is a nested relationship.

In that case you need to do the following:
- Have a resource for `ForumCategory`
- In `ForumCategory` resource you need to define the `threads` relation like Laravel [documentation suggests](https://laravel.com/docs/8.x/eloquent-resources#relationships) (meaning you also need to have a resource for `Thread`)
- In `Thread` resource you need to define the `user` relation, again the same way.
- In `User` resource you can then exclude the `email` property

**Comment by PascalHesselink** [comment] 2020-12-21 16:39
> > > @PascalHesselink,
> > > Have you tried [explicitly setting](https://tailflow.github.io/laravel-orion-docs/guide/responses.html) the resource class?
> > > If resources are located in non-conventional folder, indeed, it may not find them.
> > 
> > 
> > I'm using the default namespace/conventional way of creating resources. I've noticed if you want to manually 'register' them, they have to been put in a controller. In my case the 'user' relationship doesn't have a controller because it is a nested relationship.
> 
> In that case you need to do the following:
> 
> * Have a resource for `ForumCategory`
> * In `ForumCategory` resource you need to define the `threads` relation like Laravel [documentation suggests](https://laravel.com/docs/8.x/eloquent-resources#relationships) (meaning you also need to have a resource for `Thread`)
> * In `Thread` resource you need to define the `user` relation, again the same way.
> * In `User` resource you can then exclude the `email` property

That’s exactly what I currently have, but it still does not register/use the nested relationship’s resource in the API response.

**Comment by PascalHesselink** [comment] 2020-12-22 20:07
> > > @PascalHesselink,
> > > Have you tried [explicitly setting](https://tailflow.github.io/laravel-orion-docs/guide/responses.html) the resource class?
> > > If resources are located in non-conventional folder, indeed, it may not find them.
> > 
> > 
> > I'm using the default namespace/conventional way of creating resources. I've noticed if you want to manually 'register' them, they have to been put in a controller. In my case the 'user' relationship doesn't have a controller because it is a nested relationship.
> 
> In that case you need to do the following:
> 
> * Have a resource for `ForumCategory`
> * In `ForumCategory` resource you need to define the `threads` relation like Laravel [documentation suggests](https://laravel.com/docs/8.x/eloquent-resources#relationships) (meaning you also need to have a resource for `Thread`)
> * In `Thread` resource you need to define the `user` relation, again the same way.
> * In `User` resource you can then exclude the `email` property

Got it! I made a fault in my resource nesting, you're awesome!

**Comment by alexzarbn** [comment] 2020-12-23 15:15
This is fixed in [1.1.3 release](https://github.com/tailflow/laravel-orion/releases/tag/1.1.3).

In 1.2 release I am planning to add the ability to specify wildcard nested relations. It will remove the need for listing _all_ nested relations, if _all_ of them should be available for inclusion:

```php
protected function includes(): array
{
    return ['user', 'posts.*']; // this is NOT released yet
}
```

**Comment by joshuahill1609** [comment] 2020-12-29 14:59
I was listing out my relations four levels deep like @PascalHesselink mentioned in their comment. The new 1.1.3 breaks this for some reason, I have not been able to dive into why but wanted to leave an update in case anyone else is having the same issue. I went back to 1.1.1 and my relations load again. 
_This may be the intended functionality and I just need to change how I eager load relations._

**Comment by alexzarbn** [comment] 2020-12-30 14:10
Hi @joshuahill1609,

Thank you for brining that up. Could you please share the whitelisted includes array from your controller and the request url (with `?include=` query parameter)

**Comment by joshuahill1609** [comment] 2021-01-04 20:10
I am using the alwaysIncludes() function in the controller to always load these nested resources. 

/**
    * The relations that are loaded by default together with a resource.
    *
    * @return array
    */
    protected function alwaysIncludes() : array
    {
        return [
            'divisions', 
            'divisions.cost_codes', 
            'divisions.cost_codes.tasks', 
            'divisions.cost_codes.production_codes', 
            'divisions.cost_codes.tasks.area',
            'divisions.cost_codes.tasks.nodes',
            'divisions.cost_codes.tasks.nodes.production_codes',
            'divisions.cost_codes.tasks.manifest',
            'divisions.cost_codes.tasks.manifest.materials',
        ];
    }

**Comment by alexzarbn** [comment] 2021-01-05 10:14
@joshuahill1609,

Does the `Devision` model follow the same naming convention for defining relation methods (e.g. `cost_codes`) or it is defined as `costCodes`?

**Comment by joshuahill1609** [comment] 2021-01-06 06:09
@alexzarbn Yes, the relation method is cost_codes(). 

This is working for me now and broke when I upgraded to the new version.

**Comment by alexzarbn** [comment] 2021-01-07 07:15
@joshuahill1609,

Okay, I will dig more into this issue.

**Comment by alexzarbn** [comment] 2021-01-07 07:16
[Relations whitelisting](https://tailflow.github.io/laravel-orion-docs/guide/query-parameters.html#including-relations) using wildcards is added in [1.2](https://github.com/tailflow/laravel-orion/releases/tag/1.2) release.

**Comment by alireza2281** [comment] 2021-01-09 10:59
Hello, i have  updated to version 1.2 but when i use user.* in always include i get this error:
`Call to undefined relationship [*] on model [Modules\\User\\Entities\\User].`
and when i put these relations ['user.profile', 'user.assignedCategory'] it just fetch the last relation

**Comment by alexzarbn** [comment] 2021-01-10 06:42
Hi @alireza2281,

Whitelisting of relations using wildcards is only supported in the `includes` method.
Please upgrade to v1.2.1 - it contains the fix to make `['user.profile', 'user.assignedCategory']` whitelisting work.

**Comment by alexzarbn** [comment] 2021-01-10 06:43
@joshuahill1609,

Could you please upgrade to v1.2.1 and see, if it works? I was not able to replicate the issue though..

**Comment by alireza2281** [comment] 2021-01-11 15:10
@alexzarbn hi again,
there is one more thing that if i try to access relation from one level below the example i mentioned earlier would cause the same result problem. 
i mean if i always include `related.relatedProduct.primaryImage` and then `related.relatedProduct.variation` 
it would return just `variation`

**Comment by alexzarbn** [comment] 2021-01-14 07:58
Hi @alireza2281,

Thank you, I will look into the issue.

**Comment by alexzarbn** [comment] 2021-01-14 10:53
@alireza2281,

Recursive stuff is so confusing sometimes 😅

Please update to v1.2.2 - it should solve the problem.

**Closed by alexzarbn** 2021-01-14 10:53 UTC
Labels: enhancement
