### ISSUE TITLE
Including a relation of a polymorphic relation is not working anymore

### ISSUE THREAD

**Issue by CorentinCousse** [tailflow/laravel-orion#209] opened 2023-01-20 09:47 UTC
Hello,

@GautierDele  reported it in another issue, so I created one specifically for this problem as you asked.

The problem is, when I include a relation of a polymorphic relation , related data is not retrieved by the query.

You can look at the following example :

![image](https://user-images.githubusercontent.com/75204089/213664122-1a03751c-6a3e-4903-bdcb-4929a64efac5.png)

The 'eventable' polymorphic relation is working fine but when I want to get its status or others relations it is not retrieving them.

I tried to downgrade orion's version and I figured that the issue appeared after 2.17.0 release, it was working well before it.

My Laravel Version is 9.2.

Thanks for looking at it

**Comment by alexzarbn** [comment] 2023-01-24 09:35
Hello @CorentinCousse, @GautierDele 

The issue is fixed in [v2.19.2](https://github.com/tailflow/laravel-orion/releases/tag/2.19.2)

**Closed by alexzarbn** 2023-01-24 09:35 UTC
