### ISSUE TITLE
"This action is unauthorized." - 403 with Sanctum

### ISSUE THREAD

**Issue by MeerKatDev** [tailflow/laravel-orion#85] opened 2021-05-13 07:08 UTC
I saw other issues with this, but none helped. Here the code:

- api.php
```php
Route::middleware('auth:sanctum')->group(function() {
    Orion::resource('quotations', QuotationController::class);
...
```

 - QuotationPolicy
 ```php
<?php

namespace App\Policies;

use App\Models\User;
use App\Models\Quotation;
use Illuminate\Auth\Access\HandlesAuthorization;

class QuotationPolicy
{
    use HandlesAuthorization;

    /**
     * Determine whether the user can view any models.
     *
     * @param User $user
     * @return mixed
     */
    public function viewAny(User $user): bool
    {
        return true;
    }

    /**
     * Determine whether the user can view the model.
     *
     * @param User $user
     * @param Forum $forum
     * @return mixed
     */
    public function view(User $user, Forum $forum): bool
    {
        return true;
    }

    /**
     * Determine whether the user can create models.
     *
     * @param User $user
     * @return mixed
     */
    public function create(User $user): bool
    {
        return true;
    }
}
```

- QuotationController
```php
use App\Models\Quotation;
use Orion\Http\Requests\Request;
// use Illuminate\Http\Request;
use Orion\Http\Controllers\Controller;
// use Orion\Concerns\DisableAuthorization;

class QuotationController extends Controller
{
    protected $model = Quotation::class;

     /**
     * Retrieves currently authenticated user based on the guard.
     *
     * @return \Illuminate\Contracts\Auth\Authenticatable|null
     */
    public function resolveUser()
    {
        return Auth::guard('sanctum')->user();
    }
}
```

- AuthServiceProvider
```php
use App\Models\Quotation;
use App\Policies\QuotationPolicy;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * The policy mappings for the application.
     *
     * @var array
     */
    protected $policies = [
        Quotation::class => QuotationPolicy::class,
    ];
 ...
```

- QuotationRequest
```php

namespace App\Http\Requests;

// use App\Http\Requests\Request;
// use Illuminate\Foundation\Http\FormRequest;
use Orion\Http\Requests\Request;

class QuotationRequest extends Request
 ...
```

**Comment by MeerKatDev** [comment] 2021-05-13 07:20
If I use `Orion\Http\Requests\Request` it will give unauthorized, if I try to override `store` and simply create an object, it won't be able to get the content with `$request->all()`, although if I do `dd($request)` it shows that the `content` attribute is there. I'm testing with Postman

**Comment by mcadet** [comment] 2021-05-17 05:01
@MeerKatDev in your `config/auth.php` file, if the guard for API is like that:
```php
'api' => [
    'driver' => 'sanctum',
        'provider' => 'users',
        'hash' => false,
]
```
Use simply `auth('api')->whatever()` instead of `auth('sanctum')->whatever()`. Keep it simple, I was facing the same issue for long time.

Hope it would help!

**Comment by MeerKatDev** [comment] 2021-05-17 08:20
I tried with `Route::middleware('auth:api')->group(function() ...`, doesn't work either.

**Comment by alexzarbn** [comment] 2021-05-18 00:49
Hi @MeerKatDev,

How are you performing the requests to the API: via Postman/Insomnia or from an SPA app?

**Comment by MeerKatDev** [comment] 2021-05-18 09:32
from Postman, why is that important?

**Comment by alexzarbn** [comment] 2021-05-20 04:17
@MeerKatDev,

Sometimes 403 error is caused by misconfigured Sanctum's stateful domains.

Have you configured Sanctum correctly? Please check the following:

- Make sure `EnsureFrontendRequestsAreStateful` middleware is added to the api route group in `app/Http/Kernel.php`
- Run migrations

If none of this helps, try to create a simple route (not the Orion one) under the sanctum auth guard and see, if you still get 403 there.

Sanctum [installation docs](https://laravel.com/docs/8.x/sanctum#installation).

**Comment by MeerKatDev** [comment] 2021-05-20 21:45
> If none of this helps, try to create a simple route (not the Orion one) under the sanctum auth guard and see, if you still get 403 there.

I don't get 403 there.

**Comment by alexzarbn** [comment] 2021-05-21 04:25
@MeerKatDev 

`QuotationPolicy` is configured to use `Forum` model, not `Quotation`.
If this does not solve the issue, please ensure that the request class is not overriding `authorize` method (or ensure that this method returns true).

This is clearly not the problem with the package itself - closing the issue. Please use forums to seek help with this kind of issues.

**Closed by alexzarbn** 2021-05-21 04:25 UTC
Labels: help wanted

**Comment by MeerKatDev** [comment] 2021-05-21 06:14
> QuotationPolicy is configured to use Forum model, not Quotation.
if that was the problem, I would get some compilation error

> If this does not solve the issue, please ensure that the request class is not overriding authorize method
this was the issue, but I don't see it anywhere in the documentation that it's supposed to be a problem somehow.

**Comment by MeerKatDev** [comment] 2021-05-21 10:47
@alexzarbn it seems that this library just doesn't work with mongodb. Can you confirm?
